version: 2.1

workflows:
  flow:
    jobs:
      - docker-publish/publish:
          image: ${DOCKER_LOGIN}/circleci-kaniko
          tag: build-${CIRCLE_BUILD_NUM}
          filters:
            branches:
              only:
                - master

orbs:
  docker-publish: circleci/docker-publish@0.1.4
